[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin: $apr1$gFWC8r0q$91ZXeXIVMDIq8ByJR6Mqj1"
  ]

[http.routers.api]
  rule = "Host(`monitor.cdm-it.de`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
